version: "3.8"

services:
  database:
    container_name: skatetracker-db
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  product:
    container_name: skatetracker-api
    depends_on:
      - database
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=${API_POSTGRES_CONNECTION_STRING}
      - JWT_SECRET=${API_JWT_SECRET}
      - PORT=:8080
